CREATE TABLE IF NOT EXISTS cookies (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  ingredients TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
